#define SLVTASK_CHASSISCONTROL 			 	180
#define SLVTASK_UIDCONTROL 				 	181
#define SLVTASK_RESETTOFACTORYDEFAULT 	 	182
#define SLVTASK_QUERYFROMCPLD 			 	183 //CPLD; by linda
#define SLVTASK_UNLOCKI2C 	 			 	184
#define SLVTASK_RESETTOFACTORYDEFAULT_NOLAN	185
#define SLVTASK_APPLYUPLOADFILE_OP          186
#define SLVTASK_BIOSUPDATE				    187	
#define SLVTASK_PSTASK					    188
#define SLVTASK_SETLINKCONF					189
#define SLVTASK_OOB_CHECKSUM			    190
#define SLVTASK_PORT_CONFIG			    	191
