/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define sfcQueryconst const
#else
#define sfcQueryconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN sfcQuery_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((sfcQuery_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE sfcQueryrestart( sfcQueryin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct sfcQuery_buffer_state *YY_BUFFER_STATE;

extern int sfcQueryleng;
extern FILE *sfcQueryin, *sfcQueryout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		sfcQueryless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the sfcQueryless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define sfcQueryless(n) \
	do \
		{ \
		/* Undo effects of setting up sfcQuerytext. */ \
		*sfcQuery_cp = sfcQuery_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		sfcQuery_c_buf_p = sfcQuery_cp = sfcQuery_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up sfcQuerytext again */ \
		} \
	while ( 0 )

#define unput(c) sfcQueryunput( c, sfcQuerytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int sfcQuery_size_t;


struct sfcQuery_buffer_state
	{
	FILE *sfcQuery_input_file;

	char *sfcQuery_ch_buf;		/* input buffer */
	char *sfcQuery_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	sfcQuery_size_t sfcQuery_buf_size;

	/* Number of characters read into sfcQuery_ch_buf, not including EOB
	 * characters.
	 */
	int sfcQuery_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int sfcQuery_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int sfcQuery_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int sfcQuery_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int sfcQuery_fill_buffer;

	int sfcQuery_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via sfcQueryrestart()), so that the user can continue scanning by
	 * just pointing sfcQueryin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE sfcQuery_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER sfcQuery_current_buffer


/* sfcQuery_hold_char holds the character lost when sfcQuerytext is formed. */
static char sfcQuery_hold_char;

static int sfcQuery_n_chars;		/* number of characters read into sfcQuery_ch_buf */


int sfcQueryleng;

/* Points to current character in buffer. */
static char *sfcQuery_c_buf_p = (char *) 0;
static int sfcQuery_init = 1;		/* whether we need to initialize */
static int sfcQuery_start = 0;	/* start state number */

/* Flag which is used to allow sfcQuerywrap()'s to do buffer switches
 * instead of setting up a fresh sfcQueryin.  A bit of a hack ...
 */
static int sfcQuery_did_buffer_switch_on_eof;

void sfcQueryrestart YY_PROTO(( FILE *input_file ));

void sfcQuery_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void sfcQuery_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE sfcQuery_create_buffer YY_PROTO(( FILE *file, int size ));
void sfcQuery_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void sfcQuery_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void sfcQuery_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER sfcQuery_flush_buffer( sfcQuery_current_buffer )

YY_BUFFER_STATE sfcQuery_scan_buffer YY_PROTO(( char *base, sfcQuery_size_t size ));
YY_BUFFER_STATE sfcQuery_scan_string YY_PROTO(( sfcQueryconst char *sfcQuery_str ));
YY_BUFFER_STATE sfcQuery_scan_bytes YY_PROTO(( sfcQueryconst char *bytes, int len ));

static void *sfcQuery_flex_alloc YY_PROTO(( sfcQuery_size_t ));
static void *sfcQuery_flex_realloc YY_PROTO(( void *, sfcQuery_size_t ));
static void sfcQuery_flex_free YY_PROTO(( void * ));

#define sfcQuery_new_buffer sfcQuery_create_buffer

#define sfcQuery_set_interactive(is_interactive) \
	{ \
	if ( ! sfcQuery_current_buffer ) \
		sfcQuery_current_buffer = sfcQuery_create_buffer( sfcQueryin, YY_BUF_SIZE ); \
	sfcQuery_current_buffer->sfcQuery_is_interactive = is_interactive; \
	}

#define sfcQuery_set_bol(at_bol) \
	{ \
	if ( ! sfcQuery_current_buffer ) \
		sfcQuery_current_buffer = sfcQuery_create_buffer( sfcQueryin, YY_BUF_SIZE ); \
	sfcQuery_current_buffer->sfcQuery_at_bol = at_bol; \
	}

#define YY_AT_BOL() (sfcQuery_current_buffer->sfcQuery_at_bol)

typedef unsigned char YY_CHAR;
FILE *sfcQueryin = (FILE *) 0, *sfcQueryout = (FILE *) 0;
typedef int sfcQuery_state_type;
extern char *sfcQuerytext;
#define sfcQuerytext_ptr sfcQuerytext

static sfcQuery_state_type sfcQuery_get_previous_state YY_PROTO(( void ));
static sfcQuery_state_type sfcQuery_try_NUL_trans YY_PROTO(( sfcQuery_state_type current_state ));
static int sfcQuery_get_next_buffer YY_PROTO(( void ));
static void sfcQuery_fatal_error YY_PROTO(( sfcQueryconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up sfcQuerytext.
 */
#define YY_DO_BEFORE_ACTION \
	sfcQuerytext_ptr = sfcQuery_bp; \
	sfcQueryleng = (int) (sfcQuery_cp - sfcQuery_bp); \
	sfcQuery_hold_char = *sfcQuery_cp; \
	*sfcQuery_cp = '\0'; \
	sfcQuery_c_buf_p = sfcQuery_cp;

#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
static sfcQueryconst short int sfcQuery_accept[80] =
    {   0,
        0,    0,   32,   30,   29,   29,   30,   30,   30,   19,
       30,   19,   13,   12,   30,   24,   20,   26,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   29,   21,    0,
       18,   17,    0,   16,   15,    0,   13,   12,   14,    0,
       12,   27,   23,   22,   25,   28,   28,   28,   28,   11,
       28,   28,    9,   28,   28,   28,    0,    8,   28,   28,
       10,    7,   28,   28,   28,   28,    0,   14,   28,    2,
        6,   28,    4,   28,    5,   28,    3,    1,    0
    } ;

static sfcQueryconst int sfcQuery_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    1,    1,    6,    7,
        7,    7,    8,    7,    8,    9,    1,   10,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    1,   13,
       14,   15,    1,    1,   16,   17,   18,   19,   20,   21,
       17,   22,   23,   17,   17,   24,   25,   26,   27,   17,
       17,   28,   29,   30,   31,   17,   32,   17,   17,   17,
        1,    1,    1,    1,   17,    1,   16,   17,   18,   19,

       20,   21,   17,   22,   23,   17,   17,   24,   25,   26,
       27,   17,   17,   28,   29,   30,   31,   17,   32,   17,
       17,   17,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static sfcQueryconst int sfcQuery_meta[33] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    1,    1,    1,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2
    } ;

static sfcQueryconst short int sfcQuery_base[83] =
    {   0,
        0,    0,  121,  122,   31,   33,  106,   34,   35,  122,
       33,   35,   38,   41,  107,   39,  122,  104,   91,    0,
       39,   87,   29,   87,   94,   85,   90,   55,  122,   56,
      122,  122,   59,  122,  122,   53,   59,   62,   64,   67,
       70,  122,  122,  122,  122,    0,   92,   86,   82,   92,
       77,   82,    0,   81,   73,   83,   75,    0,   73,   76,
        0,    0,   76,   79,   78,   69,   77,   79,   76,    0,
        0,   77,    0,   62,    0,   36,    0,    0,  122,   90,
       92,   38
    } ;

static sfcQueryconst short int sfcQuery_def[83] =
    {   0,
       79,    1,   79,   79,   79,   79,   79,   80,   81,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   79,   79,   80,
       79,   79,   81,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   79,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   79,   79,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,    0,   79,
       79,   79
    } ;

static sfcQueryconst short int sfcQuery_nxt[155] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   20,   20,   20,
       21,   20,   22,   20,   20,   23,   24,   20,   25,   26,
       20,   27,   28,   28,   28,   28,   31,   34,   32,   46,
       35,   36,   37,   38,   39,   39,   36,   40,   40,   36,
       41,   41,   43,   44,   48,   51,   28,   28,   31,   52,
       32,   34,   39,   39,   35,   78,   49,   36,   40,   40,
       36,   41,   41,   39,   39,   36,   40,   40,   36,   41,
       41,   77,   67,   57,   68,   68,   68,   68,   68,   68,
       30,   30,   33,   33,   76,   75,   74,   73,   72,   71,

       70,   69,   66,   65,   64,   63,   62,   61,   60,   59,
       58,   56,   55,   54,   53,   50,   47,   45,   42,   29,
       79,    3,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79
    } ;

static sfcQueryconst short int sfcQuery_chk[155] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    5,    6,    6,    8,    9,    8,   82,
        9,   11,   11,   11,   12,   12,   13,   13,   13,   14,
       14,   14,   16,   16,   21,   23,   28,   28,   30,   23,
       30,   33,   36,   36,   33,   76,   21,   37,   37,   37,
       38,   38,   38,   39,   39,   40,   40,   40,   41,   41,
       41,   74,   57,   39,   57,   57,   67,   67,   68,   68,
       80,   80,   81,   81,   72,   69,   66,   65,   64,   63,

       60,   59,   56,   55,   54,   52,   51,   50,   49,   48,
       47,   27,   26,   25,   24,   22,   19,   18,   15,    7,
        3,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79
    } ;

static sfcQuery_state_type sfcQuery_last_accepting_state;
static char *sfcQuery_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define sfcQuerymore() sfcQuerymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *sfcQuerytext;
#line 1 "queryLexer.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#line 3 "queryLexer.l"

/*
 * queryLexer.l
 *
 * (C) Copyright IBM Corp. 2005
 *
 * THIS FILE IS PROVIDED UNDER THE TERMS OF THE ECLIPSE PUBLIC LICENSE
 * ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
 * CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
 *
 * You can obtain a current copy of the Eclipse Public License from
 * http://www.opensource.org/licenses/eclipse-1.0.php
 *
 * Author:        Adrian Schuur <schuur@de.ibm.com>
 * Based on concepts from pegasus project 
 *
 * Description:
 *
 * WQL/CQL query lexer for sfcb.
 *
*/

//%2005////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2000, 2001, 2002 BMC Software; Hewlett-Packard Development
// Company, L.P.; IBM Corp.; The Open Group; Tivoli Systems.
// Copyright (c) 2003 BMC Software; Hewlett-Packard Development Company, L.P.;
// IBM Corp.; EMC Corporation, The Open Group.
// Copyright (c) 2004 BMC Software; Hewlett-Packard Development Company, L.P.;
// IBM Corp.; EMC Corporation; VERITAS Software Corporation; The Open Group.
// Copyright (c) 2005 Hewlett-Packard Development Company, L.P.; IBM Corp.;
// EMC Corporation; VERITAS Software Corporation; The Open Group.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN
// ALL COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE. THE SOFTWARE IS PROVIDED
// "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
// ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
///////////////////////////////////////////////////////////////////////////////


extern int queryInput(char* buffer, int* numRead, int numRequested);
extern int sfcQueryErr(const char*);
extern char * sfcQueryStrcpy(char *txt, int len);

#define YY_INPUT(BUF, NREAD, NREQUESTED) queryInput(BUF, &NREAD, NREQUESTED)

#include "queryOperation.h"
#include "queryParser.h"
#include <stdio.h>
#include <string.h>

#define YY_NO_UNPUT 1

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int sfcQuerywrap YY_PROTO(( void ));
#else
extern int sfcQuerywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void sfcQueryunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef sfcQuerytext_ptr
static void sfcQuery_flex_strncpy YY_PROTO(( char *, sfcQueryconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int sfcQuery_flex_strlen YY_PROTO(( sfcQueryconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int sfcQueryinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int sfcQuery_start_stack_ptr = 0;
static int sfcQuery_start_stack_depth = 0;
static int *sfcQuery_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void sfcQuery_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void sfcQuery_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int sfcQuery_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( sfcQuerytext, sfcQueryleng, 1, sfcQueryout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( sfcQuery_current_buffer->sfcQuery_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( sfcQueryin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( sfcQueryin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, sfcQueryin )) == 0) \
		  && ferror( sfcQueryin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "sfcQueryterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef sfcQueryterminate
#define sfcQueryterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) sfcQuery_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int sfcQuerylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after sfcQuerytext and sfcQueryleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register sfcQuery_state_type sfcQuery_current_state;
	register char *sfcQuery_cp = NULL, *sfcQuery_bp = NULL;
	register int sfcQuery_act;

#line 75 "queryLexer.l"



	if ( sfcQuery_init )
		{
		sfcQuery_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! sfcQuery_start )
			sfcQuery_start = 1;	/* first start state */

		if ( ! sfcQueryin )
			sfcQueryin = stdin;

		if ( ! sfcQueryout )
			sfcQueryout = stdout;

		if ( ! sfcQuery_current_buffer )
			sfcQuery_current_buffer =
				sfcQuery_create_buffer( sfcQueryin, YY_BUF_SIZE );

		sfcQuery_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		sfcQuery_cp = sfcQuery_c_buf_p;

		/* Support of sfcQuerytext. */
		*sfcQuery_cp = sfcQuery_hold_char;

		/* sfcQuery_bp points to the position in sfcQuery_ch_buf of the start of
		 * the current run.
		 */
		sfcQuery_bp = sfcQuery_cp;

		sfcQuery_current_state = sfcQuery_start;
sfcQuery_match:
		do
			{
			register YY_CHAR sfcQuery_c = sfcQuery_ec[YY_SC_TO_UI(*sfcQuery_cp)];
			if ( sfcQuery_accept[sfcQuery_current_state] )
				{
				sfcQuery_last_accepting_state = sfcQuery_current_state;
				sfcQuery_last_accepting_cpos = sfcQuery_cp;
				}
			while ( sfcQuery_chk[sfcQuery_base[sfcQuery_current_state] + sfcQuery_c] != sfcQuery_current_state )
				{
				sfcQuery_current_state = (int) sfcQuery_def[sfcQuery_current_state];
				if ( sfcQuery_current_state >= 80 )
					sfcQuery_c = sfcQuery_meta[(unsigned int) sfcQuery_c];
				}
			sfcQuery_current_state = sfcQuery_nxt[sfcQuery_base[sfcQuery_current_state] + (unsigned int) sfcQuery_c];
			++sfcQuery_cp;
			}
		while ( sfcQuery_base[sfcQuery_current_state] != 122 );

sfcQuery_find_action:
		sfcQuery_act = sfcQuery_accept[sfcQuery_current_state];
		if ( sfcQuery_act == 0 )
			{ /* have to back up */
			sfcQuery_cp = sfcQuery_last_accepting_cpos;
			sfcQuery_current_state = sfcQuery_last_accepting_state;
			sfcQuery_act = sfcQuery_accept[sfcQuery_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( sfcQuery_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*sfcQuery_cp = sfcQuery_hold_char;
			sfcQuery_cp = sfcQuery_last_accepting_cpos;
			sfcQuery_current_state = sfcQuery_last_accepting_state;
			goto sfcQuery_find_action;

case 1:
YY_RULE_SETUP
#line 77 "queryLexer.l"
{

    return TOK_SELECT;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 82 "queryLexer.l"
{

    return TOK_FROM;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 87 "queryLexer.l"
{

    return TOK_WHERE;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 92 "queryLexer.l"
{

    return TOK_TRUE;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 97 "queryLexer.l"
{

    return TOK_FALSE;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 102 "queryLexer.l"
{

    return TOK_NULL;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 107 "queryLexer.l"
{

    return TOK_NOT;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 112 "queryLexer.l"
{

    return TOK_AND;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 117 "queryLexer.l"
{

    return TOK_OR;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 122 "queryLexer.l"
{

    return TOK_ISA;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 127 "queryLexer.l"
{

    return TOK_IS;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 132 "queryLexer.l"
{

    sfcQuerylval.intValue = strtol(sfcQuerytext, (char**)0, 10);
    return TOK_INTEGER;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 138 "queryLexer.l"
{

    sfcQuerylval.intValue = 0;
    return TOK_INTEGER;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 144 "queryLexer.l"
{

    sfcQuerylval.doubleValue = strtod((char*)sfcQuerytext, (char**)0);
    return TOK_DOUBLE;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 150 "queryLexer.l"
{

    {
       size_t n = strlen(sfcQuerytext) - 2;
       sfcQuerylval.strValue=sfcQueryStrcpy(sfcQuerytext+1,n);
    }

    return TOK_STRING;
}
	YY_BREAK
case 16:
*sfcQuery_cp = sfcQuery_hold_char; /* undo effects of setting up sfcQuerytext */
sfcQuery_c_buf_p = sfcQuery_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up sfcQuerytext again */
YY_RULE_SETUP
#line 160 "queryLexer.l"
{

    sfcQueryErr("Unterminated string");
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 165 "queryLexer.l"
{

    {
       size_t n = strlen(sfcQuerytext) - 2;
       sfcQuerylval.strValue=sfcQueryStrcpy(sfcQuerytext+1,n);
    }

    return TOK_STRING;
}
	YY_BREAK
case 18:
*sfcQuery_cp = sfcQuery_hold_char; /* undo effects of setting up sfcQuerytext */
sfcQuery_c_buf_p = sfcQuery_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up sfcQuerytext again */
YY_RULE_SETUP
#line 175 "queryLexer.l"
{

    sfcQueryErr("Unterminated string");
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 180 "queryLexer.l"
{ 

    return sfcQuerytext[0];
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 185 "queryLexer.l"
{ 
    return TOK_EQ; 
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 189 "queryLexer.l"
{ 

    return TOK_NE; 
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 195 "queryLexer.l"
{ 
    return TOK_NE; 
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 199 "queryLexer.l"
{ 
    return TOK_LE; 
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 203 "queryLexer.l"
{ 
    return TOK_LT; 
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 207 "queryLexer.l"
{ 
    return TOK_GE; 
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 211 "queryLexer.l"
{ 
    return TOK_GT; 
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 215 "queryLexer.l"
{ 
    return TOK_SCOPE; 
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 219 "queryLexer.l"
{

    {
	size_t n = strlen(sfcQuerytext);
	sfcQuerylval.strValue=sfcQueryStrcpy(sfcQuerytext,n);
    }

    return TOK_IDENTIFIER;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 229 "queryLexer.l"
{
    /* Ignore blanks */
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 233 "queryLexer.l"
{
    sfcQuerylval.intValue = 0;
    return TOK_UNEXPECTED_CHAR;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 238 "queryLexer.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	sfcQueryterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int sfcQuery_amount_of_matched_text = (int) (sfcQuery_cp - sfcQuerytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*sfcQuery_cp = sfcQuery_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( sfcQuery_current_buffer->sfcQuery_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed sfcQueryin at a new source and called
			 * sfcQuerylex().  If so, then we have to assure
			 * consistency between sfcQuery_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			sfcQuery_n_chars = sfcQuery_current_buffer->sfcQuery_n_chars;
			sfcQuery_current_buffer->sfcQuery_input_file = sfcQueryin;
			sfcQuery_current_buffer->sfcQuery_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for sfcQuery_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since sfcQuery_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( sfcQuery_c_buf_p <= &sfcQuery_current_buffer->sfcQuery_ch_buf[sfcQuery_n_chars] )
			{ /* This was really a NUL. */
			sfcQuery_state_type sfcQuery_next_state;

			sfcQuery_c_buf_p = sfcQuerytext_ptr + sfcQuery_amount_of_matched_text;

			sfcQuery_current_state = sfcQuery_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * sfcQuery_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			sfcQuery_next_state = sfcQuery_try_NUL_trans( sfcQuery_current_state );

			sfcQuery_bp = sfcQuerytext_ptr + YY_MORE_ADJ;

			if ( sfcQuery_next_state )
				{
				/* Consume the NUL. */
				sfcQuery_cp = ++sfcQuery_c_buf_p;
				sfcQuery_current_state = sfcQuery_next_state;
				goto sfcQuery_match;
				}

			else
				{
				sfcQuery_cp = sfcQuery_c_buf_p;
				goto sfcQuery_find_action;
				}
			}

		else switch ( sfcQuery_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				sfcQuery_did_buffer_switch_on_eof = 0;

				if ( sfcQuerywrap() )
					{
					/* Note: because we've taken care in
					 * sfcQuery_get_next_buffer() to have set up
					 * sfcQuerytext, we can now set up
					 * sfcQuery_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					sfcQuery_c_buf_p = sfcQuerytext_ptr + YY_MORE_ADJ;

					sfcQuery_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! sfcQuery_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				sfcQuery_c_buf_p =
					sfcQuerytext_ptr + sfcQuery_amount_of_matched_text;

				sfcQuery_current_state = sfcQuery_get_previous_state();

				sfcQuery_cp = sfcQuery_c_buf_p;
				sfcQuery_bp = sfcQuerytext_ptr + YY_MORE_ADJ;
				goto sfcQuery_match;

			case EOB_ACT_LAST_MATCH:
				sfcQuery_c_buf_p =
				&sfcQuery_current_buffer->sfcQuery_ch_buf[sfcQuery_n_chars];

				sfcQuery_current_state = sfcQuery_get_previous_state();

				sfcQuery_cp = sfcQuery_c_buf_p;
				sfcQuery_bp = sfcQuerytext_ptr + YY_MORE_ADJ;
				goto sfcQuery_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of sfcQuerylex */


/* sfcQuery_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int sfcQuery_get_next_buffer()
	{
	register char *dest = sfcQuery_current_buffer->sfcQuery_ch_buf;
	register char *source = sfcQuerytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( sfcQuery_c_buf_p > &sfcQuery_current_buffer->sfcQuery_ch_buf[sfcQuery_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( sfcQuery_current_buffer->sfcQuery_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( sfcQuery_c_buf_p - sfcQuerytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (sfcQuery_c_buf_p - sfcQuerytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( sfcQuery_current_buffer->sfcQuery_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		sfcQuery_current_buffer->sfcQuery_n_chars = sfcQuery_n_chars = 0;

	else
		{
		int num_to_read =
			sfcQuery_current_buffer->sfcQuery_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = sfcQuery_current_buffer;

			int sfcQuery_c_buf_p_offset =
				(int) (sfcQuery_c_buf_p - b->sfcQuery_ch_buf);

			if ( b->sfcQuery_is_our_buffer )
				{
				int new_size = b->sfcQuery_buf_size * 2;

				if ( new_size <= 0 )
					b->sfcQuery_buf_size += b->sfcQuery_buf_size / 8;
				else
					b->sfcQuery_buf_size *= 2;

				b->sfcQuery_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					sfcQuery_flex_realloc( (void *) b->sfcQuery_ch_buf,
							 b->sfcQuery_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->sfcQuery_ch_buf = 0;

			if ( ! b->sfcQuery_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			sfcQuery_c_buf_p = &b->sfcQuery_ch_buf[sfcQuery_c_buf_p_offset];

			num_to_read = sfcQuery_current_buffer->sfcQuery_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&sfcQuery_current_buffer->sfcQuery_ch_buf[number_to_move]),
			sfcQuery_n_chars, num_to_read );

		sfcQuery_current_buffer->sfcQuery_n_chars = sfcQuery_n_chars;
		}

	if ( sfcQuery_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			sfcQueryrestart( sfcQueryin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			sfcQuery_current_buffer->sfcQuery_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	sfcQuery_n_chars += number_to_move;
	sfcQuery_current_buffer->sfcQuery_ch_buf[sfcQuery_n_chars] = YY_END_OF_BUFFER_CHAR;
	sfcQuery_current_buffer->sfcQuery_ch_buf[sfcQuery_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	sfcQuerytext_ptr = &sfcQuery_current_buffer->sfcQuery_ch_buf[0];

	return ret_val;
	}


/* sfcQuery_get_previous_state - get the state just before the EOB char was reached */

static sfcQuery_state_type sfcQuery_get_previous_state()
	{
	register sfcQuery_state_type sfcQuery_current_state;
	register char *sfcQuery_cp;

	sfcQuery_current_state = sfcQuery_start;

	for ( sfcQuery_cp = sfcQuerytext_ptr + YY_MORE_ADJ; sfcQuery_cp < sfcQuery_c_buf_p; ++sfcQuery_cp )
		{
		register YY_CHAR sfcQuery_c = (*sfcQuery_cp ? sfcQuery_ec[YY_SC_TO_UI(*sfcQuery_cp)] : 1);
		if ( sfcQuery_accept[sfcQuery_current_state] )
			{
			sfcQuery_last_accepting_state = sfcQuery_current_state;
			sfcQuery_last_accepting_cpos = sfcQuery_cp;
			}
		while ( sfcQuery_chk[sfcQuery_base[sfcQuery_current_state] + sfcQuery_c] != sfcQuery_current_state )
			{
			sfcQuery_current_state = (int) sfcQuery_def[sfcQuery_current_state];
			if ( sfcQuery_current_state >= 80 )
				sfcQuery_c = sfcQuery_meta[(unsigned int) sfcQuery_c];
			}
		sfcQuery_current_state = sfcQuery_nxt[sfcQuery_base[sfcQuery_current_state] + (unsigned int) sfcQuery_c];
		}

	return sfcQuery_current_state;
	}


/* sfcQuery_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = sfcQuery_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static sfcQuery_state_type sfcQuery_try_NUL_trans( sfcQuery_state_type sfcQuery_current_state )
#else
static sfcQuery_state_type sfcQuery_try_NUL_trans( sfcQuery_current_state )
sfcQuery_state_type sfcQuery_current_state;
#endif
	{
	register int sfcQuery_is_jam;
	register char *sfcQuery_cp = sfcQuery_c_buf_p;

	register YY_CHAR sfcQuery_c = 1;
	if ( sfcQuery_accept[sfcQuery_current_state] )
		{
		sfcQuery_last_accepting_state = sfcQuery_current_state;
		sfcQuery_last_accepting_cpos = sfcQuery_cp;
		}
	while ( sfcQuery_chk[sfcQuery_base[sfcQuery_current_state] + sfcQuery_c] != sfcQuery_current_state )
		{
		sfcQuery_current_state = (int) sfcQuery_def[sfcQuery_current_state];
		if ( sfcQuery_current_state >= 80 )
			sfcQuery_c = sfcQuery_meta[(unsigned int) sfcQuery_c];
		}
	sfcQuery_current_state = sfcQuery_nxt[sfcQuery_base[sfcQuery_current_state] + (unsigned int) sfcQuery_c];
	sfcQuery_is_jam = (sfcQuery_current_state == 79);

	return sfcQuery_is_jam ? 0 : sfcQuery_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void sfcQueryunput( int c, register char *sfcQuery_bp )
#else
static void sfcQueryunput( c, sfcQuery_bp )
int c;
register char *sfcQuery_bp;
#endif
	{
	register char *sfcQuery_cp = sfcQuery_c_buf_p;

	/* undo effects of setting up sfcQuerytext */
	*sfcQuery_cp = sfcQuery_hold_char;

	if ( sfcQuery_cp < sfcQuery_current_buffer->sfcQuery_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = sfcQuery_n_chars + 2;
		register char *dest = &sfcQuery_current_buffer->sfcQuery_ch_buf[
					sfcQuery_current_buffer->sfcQuery_buf_size + 2];
		register char *source =
				&sfcQuery_current_buffer->sfcQuery_ch_buf[number_to_move];

		while ( source > sfcQuery_current_buffer->sfcQuery_ch_buf )
			*--dest = *--source;

		sfcQuery_cp += (int) (dest - source);
		sfcQuery_bp += (int) (dest - source);
		sfcQuery_current_buffer->sfcQuery_n_chars =
			sfcQuery_n_chars = sfcQuery_current_buffer->sfcQuery_buf_size;

		if ( sfcQuery_cp < sfcQuery_current_buffer->sfcQuery_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--sfcQuery_cp = (char) c;


	sfcQuerytext_ptr = sfcQuery_bp;
	sfcQuery_hold_char = *sfcQuery_cp;
	sfcQuery_c_buf_p = sfcQuery_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int sfcQueryinput()
#else
static int input()
#endif
	{
	int c;

	*sfcQuery_c_buf_p = sfcQuery_hold_char;

	if ( *sfcQuery_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* sfcQuery_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( sfcQuery_c_buf_p < &sfcQuery_current_buffer->sfcQuery_ch_buf[sfcQuery_n_chars] )
			/* This was really a NUL. */
			*sfcQuery_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = sfcQuery_c_buf_p - sfcQuerytext_ptr;
			++sfcQuery_c_buf_p;

			switch ( sfcQuery_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because sfcQuery_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					sfcQueryrestart( sfcQueryin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( sfcQuerywrap() )
						return EOF;

					if ( ! sfcQuery_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return sfcQueryinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					sfcQuery_c_buf_p = sfcQuerytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) sfcQuery_c_buf_p;	/* cast for 8-bit char's */
	*sfcQuery_c_buf_p = '\0';	/* preserve sfcQuerytext */
	sfcQuery_hold_char = *++sfcQuery_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void sfcQueryrestart( FILE *input_file )
#else
void sfcQueryrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! sfcQuery_current_buffer )
		sfcQuery_current_buffer = sfcQuery_create_buffer( sfcQueryin, YY_BUF_SIZE );

	sfcQuery_init_buffer( sfcQuery_current_buffer, input_file );
	sfcQuery_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void sfcQuery_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void sfcQuery_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( sfcQuery_current_buffer == new_buffer )
		return;

	if ( sfcQuery_current_buffer )
		{
		/* Flush out information for old buffer. */
		*sfcQuery_c_buf_p = sfcQuery_hold_char;
		sfcQuery_current_buffer->sfcQuery_buf_pos = sfcQuery_c_buf_p;
		sfcQuery_current_buffer->sfcQuery_n_chars = sfcQuery_n_chars;
		}

	sfcQuery_current_buffer = new_buffer;
	sfcQuery_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (sfcQuerywrap()) processing, but the only time this flag
	 * is looked at is after sfcQuerywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	sfcQuery_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void sfcQuery_load_buffer_state( void )
#else
void sfcQuery_load_buffer_state()
#endif
	{
	sfcQuery_n_chars = sfcQuery_current_buffer->sfcQuery_n_chars;
	sfcQuerytext_ptr = sfcQuery_c_buf_p = sfcQuery_current_buffer->sfcQuery_buf_pos;
	sfcQueryin = sfcQuery_current_buffer->sfcQuery_input_file;
	sfcQuery_hold_char = *sfcQuery_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE sfcQuery_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE sfcQuery_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) sfcQuery_flex_alloc( sizeof( struct sfcQuery_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in sfcQuery_create_buffer()" );

	b->sfcQuery_buf_size = size;

	/* sfcQuery_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->sfcQuery_ch_buf = (char *) sfcQuery_flex_alloc( b->sfcQuery_buf_size + 2 );
	if ( ! b->sfcQuery_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in sfcQuery_create_buffer()" );

	b->sfcQuery_is_our_buffer = 1;

	sfcQuery_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void sfcQuery_delete_buffer( YY_BUFFER_STATE b )
#else
void sfcQuery_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == sfcQuery_current_buffer )
		sfcQuery_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->sfcQuery_is_our_buffer )
		sfcQuery_flex_free( (void *) b->sfcQuery_ch_buf );

	sfcQuery_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void sfcQuery_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void sfcQuery_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	sfcQuery_flush_buffer( b );

	b->sfcQuery_input_file = file;
	b->sfcQuery_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->sfcQuery_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->sfcQuery_is_interactive = 0;
#else
	b->sfcQuery_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void sfcQuery_flush_buffer( YY_BUFFER_STATE b )
#else
void sfcQuery_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->sfcQuery_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->sfcQuery_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->sfcQuery_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->sfcQuery_buf_pos = &b->sfcQuery_ch_buf[0];

	b->sfcQuery_at_bol = 1;
	b->sfcQuery_buffer_status = YY_BUFFER_NEW;

	if ( b == sfcQuery_current_buffer )
		sfcQuery_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE sfcQuery_scan_buffer( char *base, sfcQuery_size_t size )
#else
YY_BUFFER_STATE sfcQuery_scan_buffer( base, size )
char *base;
sfcQuery_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) sfcQuery_flex_alloc( sizeof( struct sfcQuery_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in sfcQuery_scan_buffer()" );

	b->sfcQuery_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->sfcQuery_buf_pos = b->sfcQuery_ch_buf = base;
	b->sfcQuery_is_our_buffer = 0;
	b->sfcQuery_input_file = 0;
	b->sfcQuery_n_chars = b->sfcQuery_buf_size;
	b->sfcQuery_is_interactive = 0;
	b->sfcQuery_at_bol = 1;
	b->sfcQuery_fill_buffer = 0;
	b->sfcQuery_buffer_status = YY_BUFFER_NEW;

	sfcQuery_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE sfcQuery_scan_string( sfcQueryconst char *sfcQuery_str )
#else
YY_BUFFER_STATE sfcQuery_scan_string( sfcQuery_str )
sfcQueryconst char *sfcQuery_str;
#endif
	{
	int len;
	for ( len = 0; sfcQuery_str[len]; ++len )
		;

	return sfcQuery_scan_bytes( sfcQuery_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE sfcQuery_scan_bytes( sfcQueryconst char *bytes, int len )
#else
YY_BUFFER_STATE sfcQuery_scan_bytes( bytes, len )
sfcQueryconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	sfcQuery_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) sfcQuery_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in sfcQuery_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = sfcQuery_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in sfcQuery_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->sfcQuery_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void sfcQuery_push_state( int new_state )
#else
static void sfcQuery_push_state( new_state )
int new_state;
#endif
	{
	if ( sfcQuery_start_stack_ptr >= sfcQuery_start_stack_depth )
		{
		sfcQuery_size_t new_size;

		sfcQuery_start_stack_depth += YY_START_STACK_INCR;
		new_size = sfcQuery_start_stack_depth * sizeof( int );

		if ( ! sfcQuery_start_stack )
			sfcQuery_start_stack = (int *) sfcQuery_flex_alloc( new_size );

		else
			sfcQuery_start_stack = (int *) sfcQuery_flex_realloc(
					(void *) sfcQuery_start_stack, new_size );

		if ( ! sfcQuery_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	sfcQuery_start_stack[sfcQuery_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void sfcQuery_pop_state()
	{
	if ( --sfcQuery_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(sfcQuery_start_stack[sfcQuery_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int sfcQuery_top_state()
	{
	return sfcQuery_start_stack[sfcQuery_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void sfcQuery_fatal_error( sfcQueryconst char msg[] )
#else
static void sfcQuery_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine sfcQueryless() so it works in section 3 code. */

#undef sfcQueryless
#define sfcQueryless(n) \
	do \
		{ \
		/* Undo effects of setting up sfcQuerytext. */ \
		sfcQuerytext[sfcQueryleng] = sfcQuery_hold_char; \
		sfcQuery_c_buf_p = sfcQuerytext + n; \
		sfcQuery_hold_char = *sfcQuery_c_buf_p; \
		*sfcQuery_c_buf_p = '\0'; \
		sfcQueryleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef sfcQuerytext_ptr
#ifdef YY_USE_PROTOS
static void sfcQuery_flex_strncpy( char *s1, sfcQueryconst char *s2, int n )
#else
static void sfcQuery_flex_strncpy( s1, s2, n )
char *s1;
sfcQueryconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int sfcQuery_flex_strlen( sfcQueryconst char *s )
#else
static int sfcQuery_flex_strlen( s )
sfcQueryconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *sfcQuery_flex_alloc( sfcQuery_size_t size )
#else
static void *sfcQuery_flex_alloc( size )
sfcQuery_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *sfcQuery_flex_realloc( void *ptr, sfcQuery_size_t size )
#else
static void *sfcQuery_flex_realloc( ptr, size )
void *ptr;
sfcQuery_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void sfcQuery_flex_free( void *ptr )
#else
static void sfcQuery_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	sfcQuerylex();
	return 0;
	}
#endif
#line 238 "queryLexer.l"


int sfcQuerywrap()
{
    return 1;
}
