/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
static yyconst short int yy_accept[349] =
    {   0,
        0,    0,   93,   92,   84,    2,   92,   92,   90,   35,
       35,   92,   35,   86,   85,   39,   36,   41,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       92,   84,    2,   37,    0,   89,   88,    0,   86,   85,
        1,   87,    0,   85,   38,   36,   40,   91,   91,   91,
       28,   91,   91,   72,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   61,   26,   91,   91,   91,   91,   91,   91,
       31,   25,   91,   91,   91,   91,   91,   91,   91,   91,

       91,   91,   91,   91,   91,   91,   91,   22,    1,    0,
       27,   91,   24,   64,   70,   91,   91,   91,   91,   91,
       91,   91,   91,    9,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,    5,   91,   46,   91,   91,   23,   91,    9,   91,
       91,   91,   91,   91,   91,   73,   91,   55,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,    0,
       87,   91,   91,   91,    3,   10,   91,   91,   91,   91,
       12,   91,   91,   91,   71,   91,   91,   42,   91,   91,
       91,   91,   91,   91,   16,   34,   91,   91,   91,   91,

       58,   30,   32,   62,   20,   91,   69,   91,   91,    7,
       91,   91,   73,   91,   91,   63,   91,   13,   18,   91,
       91,   91,   91,   91,   91,   83,   44,   91,   91,   52,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       19,   68,   75,   91,    0,   67,   91,   91,   91,   91,
        0,   91,   74,   91,   91,   91,   33,   91,   91,   43,
       91,   77,   91,   91,   91,   91,   17,   91,    6,   21,
       91,   45,   91,   91,   57,   91,    8,   79,   65,   91,
        0,   76,   54,   91,   91,    0,   91,   91,   91,   91,
        0,   15,   91,   91,   91,   48,   56,   59,   91,   66,

       91,    9,   60,   91,   91,   47,    0,    5,   91,    0,
        9,   53,   49,   91,    0,   91,   91,   91,   11,   91,
       29,   91,    0,   91,    0,   91,    0,    4,   91,   78,
       91,   80,    0,   81,    0,   91,    0,   14,   50,   34,
       91,   32,   51,    0,   91,   33,   82,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    1,    1,    8,    8,
        8,    8,    9,    8,   10,   11,    1,   12,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    8,    1,   14,
       15,   16,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
        1,    1,    1,    1,   42,    1,   43,   18,   19,   20,

       21,   22,   23,   24,   25,   26,   27,   44,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,    1,   45,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[46] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    3,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1
    } ;

static yyconst short int yy_base[353] =
    {   0,
        0,    0,  439,  440,   44,    0,  423,   44,  440,  440,
       40,   44,   46,   49,   52,   51,  422,  421,   40,   48,
       54,   62,  395,   89,  400,   55,   46,  402,  411,   61,
        0,   43,   60,  397,   70,   71,   82,   79,   60,   88,
      385,  113,    0,  440,  115,  440,  440,  115,  118,  122,
        0,  124,  127,  130,  440,  440,  440,    0,  116,  126,
      410,  392,  404,    0,   80,  130,  396,  404,  388,  131,
      388,  385,  390,  129,  121,  384,  385,  384,  386,  127,
      385,  377,  121,    0,  389,  372,  390,  384,  374,  133,
      130,  389,  383,  146,  384,  367,  136,  152,  376,  386,

      374,  365,  376,  380,  142,  378,  362,  440,    0,  169,
        0,  376,    0,    0,    0,  357,  370,  155,  360,  374,
      165,  168,  371,  366,  170,  369,  370,  352,  369,  354,
      364,  349,  348,  363,  346,  359,  350,  160,  341,  352,
      355,  170,  345,    0,  338,  352,    0,  162,  351,  330,
      349,  340,  164,  347,  343,  331,  344,    0,  165,  343,
      166,  342,  341,  165,  180,  324,  341,  325,  334,  190,
      202,  323,  335,  325,    0,    0,  327,  188,  317,  316,
        0,  322,  313,  313,    0,  323,  184,    0,  315,  310,
      324,  320,  307,  317,    0,  337,  308,  309,  304,  184,

        0,    0,  333,    0,    0,  302,    0,  301,  199,    0,
      300,  297,    0,  313,  189,    0,  310,  295,    0,  299,
      291,  291,  305,  301,  303,    0,    0,  302,  286,    0,
      285,  286,  298,  202,  193,  297,  287,  295,  279,  279,
        0,    0,    0,  290,  281,    0,  288,  274,  288,  273,
      276,  281,    0,  271,  270,  282,  298,  265,  275,    0,
      263,  205,  277,  276,  261,  207,    0,  265,    0,    0,
      208,    0,  199,  258,    0,  274,    0,  209,    0,  262,
      254,    0,    0,  256,  268,  251,  268,  245,  244,  254,
      252,    0,  252,  212,  202,    0,    0,    0,  247,    0,

      255,    0,    0,  243,  210,    0,  242,    0,  258,  240,
        0,    0,    0,  256,  237,  237,  242,  215,    0,  235,
        0,  212,  241,  225,  237,  232,  213,    0,  212,    0,
      203,    0,  202,  217,  201,   87,   98,    0,    0,  440,
      213,  440,    0,   70,  219,  440,    0,  440,  263,  266,
       46,  269
    } ;

static yyconst short int yy_def[353] =
    {   0,
      348,    1,  348,  348,  348,  349,  348,  350,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      348,  348,  349,  348,  350,  348,  348,  348,  348,  348,
      352,  348,  348,  348,  348,  348,  348,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  351,  348,  352,  348,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  348,
      348,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  348,  351,  351,  351,  351,  351,
      348,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      348,  351,  351,  351,  351,  348,  351,  351,  351,  351,
      348,  351,  351,  351,  351,  351,  351,  351,  351,  351,

      351,  351,  351,  351,  351,  351,  348,  351,  351,  348,
      351,  351,  351,  351,  348,  351,  351,  351,  351,  351,
      351,  351,  348,  351,  348,  351,  348,  351,  351,  351,
      351,  351,  348,  351,  348,  351,  348,  351,  351,  348,
      351,  348,  351,  348,  351,  348,  351,    0,  348,  348,
      348,  348
    } ;

static yyconst short int yy_nxt[486] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   31,   35,   36,   37,   38,   39,   40,   31,
       31,   31,   19,   30,   41,   42,   46,   42,   58,   47,
       48,   49,   50,   51,   48,   49,   50,   52,   52,   48,
       53,   53,   48,   54,   54,   55,   44,   59,   62,   60,
       65,   82,   63,   89,   61,   83,  105,   66,   69,   90,
       84,   87,   70,   59,   67,   88,   71,   68,   64,   91,
       94,   97,   72,   92,   95,   73,   65,   82,  100,   98,

       96,   99,  105,  346,   69,   75,  101,  118,  103,   76,
      104,  106,  107,   77,   42,  102,   42,   46,  344,   78,
       47,  343,   79,  118,  100,   80,   52,   52,   48,   53,
       53,   75,   48,   54,   54,   52,   52,   48,   53,   53,
       48,   54,   54,  111,  110,  113,  119,  131,  133,  124,
      120,  112,  125,  132,  138,  141,  142,  150,  126,  111,
      148,  149,  153,  157,  133,  127,  114,  154,  159,  166,
      138,  158,  119,  150,  126,  167,  148,  170,  170,  157,
      171,  171,  175,  178,  180,  166,  183,  196,  153,  205,
      200,  210,  215,  217,  159,  220,  222,  221,  175,  179,

      201,  171,  171,  196,  231,  205,  249,  210,  215,  217,
      180,  238,  183,  171,  171,  254,  259,  250,  273,  255,
      274,  295,  222,  299,  301,  305,  302,  238,  317,  318,
      231,  330,  259,  341,  342,  340,  274,  322,  339,  332,
      345,  254,  302,  338,  273,  318,  347,  295,  337,  299,
      301,  305,  336,  322,  317,  332,  345,  335,  330,  341,
      334,  333,  347,   43,  331,   43,   45,   45,   45,  109,
      329,  109,  328,  327,  326,  325,  324,  323,  321,  320,
      319,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  304,  303,  300,  298,  297,  296,  294,  293,

      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  272,  271,
      270,  269,  268,  267,  266,  265,  264,  263,  262,  261,
      260,  258,  257,  256,  253,  252,  251,  248,  247,  246,
      245,  244,  243,  242,  241,  240,  239,  237,  236,  235,
      234,  233,  232,  230,  229,  228,  227,  226,  225,  224,
      223,  219,  218,  216,  214,  213,  212,  211,  209,  208,
      207,  206,  204,  203,  202,  199,  198,  197,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      182,  181,  177,  176,  174,  173,  172,  169,  168,  165,

      164,  163,  162,  161,  160,  156,  155,  152,  151,  147,
      146,  145,  144,  143,  140,  139,  137,  136,  135,  134,
      130,  129,  128,  123,  122,  121,  117,  116,  115,  108,
       93,   86,   85,   81,   74,   57,   56,   44,  348,    3,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348
    } ;

static yyconst short int yy_chk[486] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    8,    5,  351,    8,
       11,   11,   11,   12,   12,   12,   12,   13,   13,   14,
       14,   14,   15,   15,   15,   16,   16,   19,   20,   19,
       21,   26,   20,   32,   19,   27,   39,   21,   22,   32,
       27,   30,   22,   19,   21,   30,   22,   21,   20,   33,
       35,   36,   22,   33,   35,   22,   21,   26,   37,   36,

       35,   36,   39,  344,   22,   24,   37,   65,   38,   24,
       38,   40,   40,   24,   42,   37,   42,   45,  337,   24,
       45,  336,   24,   65,   37,   24,   48,   48,   49,   49,
       49,   24,   50,   50,   50,   52,   52,   53,   53,   53,
       54,   54,   54,   59,   52,   60,   66,   74,   75,   70,
       66,   59,   70,   74,   80,   83,   83,   91,   70,   59,
       90,   90,   94,   97,   75,   70,   60,   94,   98,  105,
       80,   97,   66,   91,   70,  105,   90,  110,  110,   97,
      110,  110,  118,  121,  122,  105,  125,  138,   94,  148,
      142,  153,  159,  161,   98,  164,  165,  164,  118,  121,

      142,  170,  170,  138,  178,  148,  200,  153,  159,  161,
      122,  187,  125,  171,  171,  209,  215,  200,  234,  209,
      235,  262,  165,  266,  271,  278,  273,  187,  294,  295,
      178,  318,  215,  334,  335,  333,  235,  305,  331,  322,
      341,  209,  273,  329,  234,  295,  345,  262,  327,  266,
      271,  278,  326,  305,  294,  322,  341,  325,  318,  334,
      324,  323,  345,  349,  320,  349,  350,  350,  350,  352,
      317,  352,  316,  315,  314,  310,  309,  307,  304,  301,
      299,  293,  291,  290,  289,  288,  287,  286,  285,  284,
      281,  280,  276,  274,  268,  265,  264,  263,  261,  259,

      258,  257,  256,  255,  254,  252,  251,  250,  249,  248,
      247,  245,  244,  240,  239,  238,  237,  236,  233,  232,
      231,  229,  228,  225,  224,  223,  222,  221,  220,  218,
      217,  214,  212,  211,  208,  206,  203,  199,  198,  197,
      196,  194,  193,  192,  191,  190,  189,  186,  184,  183,
      182,  180,  179,  177,  174,  173,  172,  169,  168,  167,
      166,  163,  162,  160,  157,  156,  155,  154,  152,  151,
      150,  149,  146,  145,  143,  141,  140,  139,  137,  136,
      135,  134,  133,  132,  131,  130,  129,  128,  127,  126,
      124,  123,  120,  119,  117,  116,  112,  107,  106,  104,

      103,  102,  101,  100,   99,   96,   95,   93,   92,   89,
       88,   87,   86,   85,   82,   81,   79,   78,   77,   76,
       73,   72,   71,   69,   68,   67,   63,   62,   61,   41,
       34,   29,   28,   25,   23,   18,   17,    7,    3,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "sqlLexer.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#line 3 "sqlLexer.l"
/*
 * sqlLexer.l
 *
 * (C) Copyright IBM Corp. 2005
 *
 * THIS FILE IS PROVIDED UNDER THE TERMS OF THE ECLIPSE PUBLIC LICENSE
 * ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE
 * CONSTITUTES RECIPIENTS ACCEPTANCE OF THE AGREEMENT.
 *
 * You can obtain a current copy of the Eclipse Public License from
 * http://www.opensource.org/licenses/eclipse-1.0.php
 *
 * Author:       Sebastian Seyrich <seyrich@de.ibm.com>
 *
 * Description:
 * 
 *
 * 
 *
*/

extern int sqlInput(char* buffer, int* numRead, int numRequested);
extern int yyErr(const char*);
extern char * yyStrcpy(char *txt, int len);
extern void setSqlWarning(char* s, char *r);

#undef YY_INPUT
#define YY_INPUT(BUF, NREAD, NREQUESTED) sqlInput(BUF, &NREAD, NREQUESTED)



#include "queryOperation.h"
#include "sqlParser.h"
#include "sqlStatement.h"
#include <stdio.h>
#include <string.h>

#if 0
# define QL_TRACE(X) printf X
#else
# define QL_TRACE(X)
#endif

//extern SqlWarning* Sw;

#define MAXBUF 500

char linebuf[MAXBUF];
int lineno=0;
int tokenpos=0;

#line 637 "sqlLexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 61 "sqlLexer.l"


#line 791 "sqlLexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 349 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 440 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "sqlLexer.l"
/* comment */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 66 "sqlLexer.l"
{
	strcpy(linebuf, yytext+1);//save next line	
	lineno++;
	tokenpos = 0;
	yyless(1);//alles außer dem \n zum erneuten Scannen zurückgeben
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "sqlLexer.l"
{
	tokenpos+=yyleng;
	return TOK_CALL;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 79 "sqlLexer.l"
{
	tokenpos+=yyleng;
	return TOK_SINTDT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 84 "sqlLexer.l"
{
	tokenpos+=yyleng;
	return TOK_INTDT;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 89 "sqlLexer.l"
{
	tokenpos+=yyleng;
	return TOK_BINTDT;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 94 "sqlLexer.l"
{
	tokenpos+=yyleng;
	return TOK_REALDT;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 99 "sqlLexer.l"
{
	tokenpos+=yyleng;
	return TOK_DOUBLEDT;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 104 "sqlLexer.l"
{
	tokenpos+=yyleng;
	return TOK_DECDT;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 109 "sqlLexer.l"
{
	tokenpos+=yyleng;
	return TOK_CHARDT;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 114 "sqlLexer.l"
{
	tokenpos+=yyleng;
	return TOK_VCHARDT;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 119 "sqlLexer.l"
{
	tokenpos+=yyleng;
	return TOK_DATEDT;
} 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 124 "sqlLexer.l"
{
	tokenpos+=yyleng;
	return TOK_TIMEDT;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 129 "sqlLexer.l"
{
	tokenpos+=yyleng;
	return TOK_TSTAMPDT;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 134 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_SELECT]\n", yytext));
    tokenpos+=yyleng;
	return TOK_SELECT;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 141 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_FROM]\n", yytext));
    tokenpos+=yyleng;
	return TOK_FROM;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 148 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_WHERE]\n", yytext));
    tokenpos+=yyleng;
	return TOK_WHERE;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 155 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_TRUE]\n", yytext));
    tokenpos+=yyleng;
	return TOK_TRUE;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 162 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_FALSE]\n", yytext));
    tokenpos+=yyleng;
	return TOK_FALSE;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 169 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_NULL]\n", yytext));
    tokenpos+=yyleng;
	return TOK_NULL;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 176 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_CONCAT]\n", yytext));
    tokenpos+=yyleng;
	return TOK_CONCAT;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 182 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_CONCAT]\n", yytext));
    tokenpos+=yyleng;
	return TOK_CONCAT;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 189 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_NOT]\n", yytext));
    tokenpos+=yyleng;
	return TOK_NOT;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 196 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_AND]\n", yytext));
    tokenpos+=yyleng;
	return TOK_AND;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 203 "sqlLexer.l"
{

   QL_TRACE(("LEX: %s [TOK_OR]\n", yytext));
    tokenpos+=yyleng;
	return TOK_OR;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 210 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_IS]\n", yytext));
    tokenpos+=yyleng;
	return TOK_IS;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 217 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_ALL]\n", yytext));
    tokenpos+=yyleng;
	return TOK_ALL;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 224 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_AS]\n", yytext));
    tokenpos+=yyleng;
	return TOK_AS;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 231 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [TOK_DISTINCT]\n", yytext));
    tokenpos+=yyleng;
	return TOK_DISTINCT;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 238 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_JOIN]\n", yytext));
	tokenpos+=yyleng;
	return TOK_JOIN;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 245 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_ON]\n", yytext));
	tokenpos+=yyleng;
	return TOK_ON;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 252 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_LEFT]\n", yytext));
	tokenpos+=yyleng;
	return TOK_LEFT;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 259 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_RIGHT]\n", yytext));
	tokenpos+=yyleng;
	return TOK_RIGHT;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 266 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_FULL]\n", yytext));
	tokenpos+=yyleng;
	return TOK_FULL;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 276 "sqlLexer.l"
{ 

QL_TRACE(("LEX: %s [???]\n", yytext));
   tokenpos+=yyleng;
	return yytext[0];
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 283 "sqlLexer.l"
{ 
	QL_TRACE(("LEX: %s [TOK_EQ]\n", yytext));   
    tokenpos+=yyleng;
	return TOK_EQ; 
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 289 "sqlLexer.l"
{ 

	QL_TRACE(("LEX: %s [TOK_NE]\n", yytext));    
    tokenpos+=yyleng;
	return TOK_NE; 
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 297 "sqlLexer.l"
{ 

    QL_TRACE(("LEX: %s [TOK_LE]\n", yytext));
    tokenpos+=yyleng;
	return TOK_LE; 
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 304 "sqlLexer.l"
{ 

    QL_TRACE(("LEX: %s [TOK_LT]\n", yytext));
    tokenpos+=yyleng;
	return TOK_LT; 
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 311 "sqlLexer.l"
{ 

    QL_TRACE(("LEX: %s [TOK_GE]\n", yytext));
    tokenpos+=yyleng;
	return TOK_GE; 
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 318 "sqlLexer.l"
{ 

    QL_TRACE(("LEX: %s [TOK_GT]\n", yytext));
    tokenpos+=yyleng;
	return TOK_GT; 
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 325 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_DROP]\n", yytext));
	tokenpos+=yyleng;
	return TOK_DROP; 
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 332 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_TABLE]\n", yytext));
	tokenpos+=yyleng;
	return TOK_TABLE; 
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 339 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_ALTER]\n", yytext));
	tokenpos+=yyleng;
	return TOK_ALTER; 
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 346 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_CREATE]\n", yytext));
	tokenpos+=yyleng;
	return TOK_CREATE; 
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 354 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_KEY]\n", yytext));
	tokenpos+=yyleng;
	return TOK_KEY; 
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 361 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_FOREIGN]\n", yytext));
	tokenpos+=yyleng;
	return TOK_FOREIGN; 
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 368 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_UNIQUE]\n", yytext));
	tokenpos+=yyleng;
	return TOK_UNIQUE; 
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 375 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_PRIMARY]\n", yytext));
	tokenpos+=yyleng;
	return TOK_PRIMARY; 
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 382 "sqlLexer.l"
{
	
	QL_TRACE(("LEX: %s [TOK_CONSTRAINT]\n", yytext));
	tokenpos+=yyleng;
	return TOK_CONSTRAINT; 
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 389 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_REFERENCES]\n", yytext));
	tokenpos+=yyleng;
	return TOK_REFERENCES; 
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 396 "sqlLexer.l"
{
	
	QL_TRACE(("LEX: %s [TOK_CHECK]\n", yytext));
	tokenpos+=yyleng;
	return TOK_CHECK; 
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 403 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_PRIMARY]\n", yytext));
	tokenpos+=yyleng;
	return TOK_PRIMARY; 
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 410 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_INSERT]\n", yytext));
	tokenpos+=yyleng;
	return TOK_INSERT; 
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 417 "sqlLexer.l"
{
	
	QL_TRACE(("LEX: %s [TOK_SET]\n", yytext));
	tokenpos+=yyleng;printf("set\n");
	return TOK_SET; 
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 424 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_UPDATE]\n", yytext));
	tokenpos+=yyleng;
	return TOK_UPDATE; 
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 432 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_DELETE]\n", yytext));
	tokenpos+=yyleng;
	return TOK_DELETE; 
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 439 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_INTO]\n", yytext));
	tokenpos+=yyleng;
	return TOK_INTO; 
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 446 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_VALUES]\n", yytext));
	tokenpos+=yyleng;
	return TOK_VALUES; 
}	
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 453 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_DEFAULT]\n", yytext));
	tokenpos+=yyleng;
	return TOK_DEFAULT; 
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 461 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_IN]\n", yytext));
	tokenpos+=yyleng;
	return TOK_IN; 
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 468 "sqlLexer.l"
{
	
	QL_TRACE(("LEX: %s [TOK_LIKE]\n", yytext));
	tokenpos+=yyleng;
	return TOK_LIKE; 
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 475 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_SOME]\n", yytext));
	tokenpos+=yyleng;
	return TOK_SOME; 
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 482 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_ANY]\n", yytext));
	tokenpos+=yyleng;
	return TOK_ANY; 
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 489 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_EXISTS]\n", yytext));
	tokenpos+=yyleng;
	return TOK_EXISTS; 
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 496 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_BETWEEN]\n", yytext));
	tokenpos+=yyleng;
	return TOK_BETWEEN; 
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 503 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_GROUP]\n", yytext));
	tokenpos+=yyleng;
	return TOK_GROUP; 
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 510 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_FETCH]\n", yytext));
	tokenpos+=yyleng;
	return TOK_FETCH; 
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 517 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_ONLY]\n", yytext));
	tokenpos+=yyleng;
	return TOK_ONLY; 
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 524 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_ASC]\n", yytext));
	tokenpos+=yyleng;
	return TOK_ASC; 
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 531 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_DESC]\n", yytext));
	tokenpos+=yyleng;
	return TOK_DESC; 
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 538 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_BY]\n", yytext));
	tokenpos+=yyleng;
	return TOK_BY; 
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 545 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_ROWS]\n", yytext));
	tokenpos+=yyleng;
	return TOK_ROW; 
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 552 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_ORDER]\n", yytext));
	tokenpos+=yyleng;
	return TOK_ORDER; 
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 559 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_FIRST]\n", yytext));
	tokenpos+=yyleng;
	return TOK_FIRST; 
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 566 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_HAVING]\n", yytext));
	tokenpos+=yyleng;
	return TOK_HAVING; 
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 574 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_UNION]\n", yytext));
	tokenpos+=yyleng;
	return TOK_UNION; 
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 580 "sqlLexer.l"
{

	QL_TRACE(("LEX: %s [TOK_UNIONALL]\n", yytext));
	tokenpos+=yyleng;
	return TOK_UNIONALL; 
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 587 "sqlLexer.l"
{
	
	QL_TRACE(("LEX: %s [TOK_EXCEPT]\n", yytext));
	tokenpos+=yyleng;
	return TOK_EXCEPT; 
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 593 "sqlLexer.l"
{
	
	QL_TRACE(("LEX: %s [TOK_EXCEPTALL]\n", yytext));
	tokenpos+=yyleng;
	return TOK_EXCEPTALL; 
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 600 "sqlLexer.l"
{ 

	QL_TRACE(("LEX: %s [TOK_INTERSECT]\n", yytext));
	tokenpos+=yyleng;
	return TOK_INTERSECT; 
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 607 "sqlLexer.l"
{ 

	QL_TRACE(("LEX: %s [TOK_INTERSECTALL]\n", yytext));
	tokenpos+=yyleng;
	return TOK_INTERSECTALL; 
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 614 "sqlLexer.l"
{ 

	QL_TRACE(("LEX: %s [TOK_WITH]\n", yytext));
	tokenpos+=yyleng;
	return TOK_WITH; 
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 624 "sqlLexer.l"
{
	tokenpos+=yyleng;
	
    /* Ignore blanks */
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 632 "sqlLexer.l"
{
	QL_TRACE(("LEX: %s [???1]\n", yytext));
    yylval.intValue = strtol(yytext, (char**)0, 10);
    tokenpos+=yyleng;
    return TOK_INTEGER;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 639 "sqlLexer.l"
{
	QL_TRACE(("LEX: %s [???1]\n", yytext));
    yylval.intValue = 0;
    tokenpos+=yyleng;
    return TOK_INTEGER;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 647 "sqlLexer.l"
{

    
     yylval.doubleValue = strtod((char*)yytext, (char**)0);
     
    tokenpos+=yyleng;
	return TOK_DOUBLE;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 656 "sqlLexer.l"
{

    QL_TRACE(("LEX: %s [???2]\n", yytext));
    size_t n = strlen(yytext) - 2;
    char* str=(char*)malloc(n+1);
   memcpy(str,yytext+1,n);
   str[n]=0;
  
    yylval.strValue=str;
    tokenpos+=yyleng;
	return TOK_STRING;
}
	YY_BREAK
case 89:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 669 "sqlLexer.l"
{
  QL_TRACE(("LEX: %s [???3]\n", yytext));
 tokenpos+=yyleng;
	   
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 675 "sqlLexer.l"
{return '$';}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 677 "sqlLexer.l"
{

 //   QL_TRACE(("LEX: %s [TOK_IDENTIFIER]\n", yytext));

    {
    tokenpos+=yyleng;
	size_t n = strlen(yytext);
	yylval.strValue=sfcQueryStrcpy(yytext,n);
    }

    return TOK_IDENTIFIER;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 692 "sqlLexer.l"
ECHO;
	YY_BREAK
#line 1769 "sqlLexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 349 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 349 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 348);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 692 "sqlLexer.l"


/*/ergänzt die Nachricht  m um die Positionsangabe des zuletzt gelesenen Zeichens*/
void yyerror(char *m){
	//char* ss;
	
	char* r; 
	char z[5];
	char s[5];
	char p[MAXBUF];
	int zi, si, pi;
	tokenpos-=yyleng;
	
	zi = sprintf(z,"%d",lineno);
	si = sprintf(s,"%d",tokenpos);
	pi = sprintf(p,"%*s\n",1+tokenpos,"^");
	
	
	r = (char *) malloc(strlen(m)+21+strlen(linebuf)+zi+si+pi+1);
	strcpy(r,"Zeile ");
	strncat(r,z,zi);
	strcat(r,", Spalte ");
	strncat(r,s,si);
	strcat(r,": ");
	strcat(r,m);
	strcat(r,"\n\t");
	strncat(r,linebuf,strlen(linebuf));
	strcat(r,"\n\t");
	strncat(r,p,pi);
	
	//printf("Zeile %d, Spalte %d: %s: \n%s\n",lineno,tokenpos,s,linebuf);
	//printf("%*s\n---\n",1+tokenpos,"^");
	//printf("%s",r);
//	RS->meta="kk";
//printf("%p\n",yylval.stm);
	//if(yylval.stm!=NULL&&strcmp("!!!!!",stm->rs->sw->sqlstate)==0){
	//	stm->rs->sw->reason = r;
	//}
	//else{
		//printf("adad\n");
		setSqlWarning("11111",r);
	//}
	//printf("2\n");
	
}

int yywrap()
{
    return 1;
}

