-include $(PRJ_PATH)/.config
-include $(PRJ_PATH)/.machine
WEB_PATH = $(PRJ_PATH)/Web_Server
PRJ_CGI_PATH = $(PRJ_PATH)/Web_Server/OS/Linux/Host/$(MYMCU)/Board/$(BOARD)
CGILIBPATH=$(PRJ_PATH)/Web_Server/OS/Linux/

all:
	@echo "******************** build web cgi ********************"

install:
	@echo "******************** install web cgi ********************"

clean:
	@echo "******************** clean web data ********************"
