.TH  3  2005-06-09 "sfcc" "SFCBroker Client Library"
.SH NAME
CMCIClientFT.execQuery() \- Query the enumeration of instances of a class
.SH SYNOPSIS
.nf
.B #include <cmci.h>
.sp
.BI CMPIEnumeration *
.BI CMCIClientFT.execQuery (CMCIClient* cl,
.br
.BI				CMPIObjectPath* op,
.br
.BI				const char* query,
.br
.BI				const char* lang,
.br
.BI				CMPIStatus* rc);
.br
.sp
.fi
.SH DESCRIPTION
Query the enumeration of instances of the class (and subclasses) defined
by reference \fIop\fP using the \fIquery\fP expression.
.PP
Arguments are the client object pointer \fIcl\fP, an ObjectPath object 
pointer \fIop\fP with the reference that contains namespace and classname
components,
the query expression string pointer in \fIquery\fP,
the query language identifier string pointer in \fIlang\fP,
and \fIrc\fP which returns the operation status (suppressed when NULL).
.PP
.SH "RETURN VALUE"
When successful the \fBCMCIClientFT.execQuery()\fP function returns a
pointer to a CMPIEnumeration object that contains the class instances 
that match the query and sets a successful operation status code.
When unsuccessful it returns a NULL pointer and sets the operation 
status error code and corresponding error string in \fIrc\fP.
.SH "ERRORS"
.sp
.SH "EXAMPLES"
.sp
.SH "CONFORMING TO"
.sp
.SH "SEE ALSO"
Common Manageability Programming Interface (CMPI) - OpenGroup,
.br
CMCIClient(3), CMPIEnumeration(3), CMPIObjectPath(3), CMPIStatus(3)
