#!/bin/bash
#
# $Id: sfcb.init-redhat.in,v 1.2 2005/06/13 12:50:33 mihajlov Exp $
#
# chkconfig: 35 20 80
#
# description: Small Footprint CIM Broker Service
#
# processname: sfcbd
#
# config: /SFCBx86/local/etc/sfcb/sfcb.cfg

# Source function library.
. /etc/init.d/functions

echo $PATH | grep -q /SFCBx86/local/sbin ||PATH=/SFCBx86/local/sbin:$PATH

if [ -z "$LD_LIBRARY_PATH" ] || echo $LD_LIBRARY_PATH | grep -qv /root/ATEN/source/OEM/STD_V317_LOGO/STD_X9_237_Security_X10/SDK/SFCB/SFCBx86/local/lib
then
    LD_LIBRARY_PATH=/root/ATEN/source/OEM/STD_V317_LOGO/STD_X9_237_Security_X10/SDK/SFCB/SFCBx86/local/lib:$LD_LIBRARY_PATH
    export LD_LIBRARY_PATH
fi

start() {
	echo -n "Starting sfcb: "
	daemon /SFCBx86/local/sbin/sfcbd -d &&
	touch /var/lock/subsys/sfcb &&
	return 0 ||
	return 1
}	

stop() {
	echo -n "Shutting down sfcb: "
	killproc sfcbd &&
	rm -f /var/lock/subsys/sfcb &&
	return 0 || return 1
}

reload() {
	echo -n "Reloading sfcb configuration: "
	killproc sfcbd -HUP &&
	return 0 || return 1
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	status sfcbd
	;;
    restart)
    	stop
	start
	;;
    reload)
	reload
	;;
    condrestart)
	[ -f /var/lock/subsys/sfcb ] && restart || :
	;;
    *)
	echo "Usage: sfcb {start|stop|status|reload|restart|condrestart}"
	exit 1
	;;
esac
exit $?
